# Generated by Django 4.1.7 on 2023-03-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_board', to='kanban.board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_row',
                                    to='kanban.row'),
        ),
    ]
