# Generated by Django 4.1.7 on 2023-03-26 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='card_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
