# Generated by Django 4.1.7 on 2023-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='rows',
            field=models.ManyToManyField(related_name='rows', related_query_name='rows', to='kanban.row'),
        ),
    ]
