# Generated by Django 4.1.7 on 2023-02-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_board', to='kanban.board'),
        ),
    ]
