# Generated by Django 4.1.7 on 2023-03-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_board_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='rows',
        ),
    ]
