# Generated by Django 4.1.7 on 2023-03-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_board_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_static',
        ),
    ]
