# Generated by Django 4.1.7 on 2023-02-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_card_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['index']},
        ),
    ]
