# Generated by Django 4.1.7 on 2023-03-27 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_card_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='card_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_item', to='kanban.card'),
        ),
    ]
