# Generated by Django 4.1.7 on 2023-03-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_card_users_alter_carditem_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_card_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='parent_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_parent_card', to='kanban.card'),
        ),
    ]
