# Generated by Django 4.1.7 on 2023-03-11 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_remove_board_is_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='name',
            field=models.CharField(default=21, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_row', to='kanban.row'),
        ),
    ]
