# Generated by Django 4.1.7 on 2023-03-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_card_is_card_completed_card_parent_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='restricted_boards',
            field=models.ManyToManyField(blank=True, related_name='card_board_restricted', to='kanban.board'),
        ),
    ]
