# Generated by Django 4.1.7 on 2023-03-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_card_restricted_boards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['id']},
        ),
    ]
