# Generated by Django 4.1.7 on 2023-03-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_board_name_alter_row_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('is_done', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_item', to='kanban.card')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
