# Generated by Django 4.1.7 on 2023-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_board_name_alter_row_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
