# Generated by Django 4.1.7 on 2023-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://u.cubeupload.com/dawid8374/genericavatar.png', max_length=200),
        ),
    ]
