# Generated by Django 4.1.7 on 2023-04-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_row_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='card',
            name='has_bug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_card_finished',
            field=models.BooleanField(default=False),
        ),
    ]
