# Generated by Django 4.1.7 on 2023-03-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('avatar', models.CharField(default='https://u.cubeupload.com/dawid8374/genericavatar.png', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
