# Generated by Django 4.1.7 on 2023-03-18 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kanban', '0008_parameter'),
    ]

    operations = [
    ]
