# Generated by Django 4.1.7 on 2023-04-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_cardmovetimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='min_card',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
