# Generated by Django 4.1.7 on 2023-03-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20230318_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='avatar',
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
