# Generated by Django 4.1.7 on 2023-03-18 00:48

from django.db import migrations


def load_initial_data(apps,something):
    parameter_model = apps.get_model('kanban','Parameter')
    parameter_model.objects.create(
        name="limit", value=2, id=1
    )

class Migration(migrations.Migration):
    dependencies = [
        ('kanban', '0010_remove_parameter_avatar_parameter_value'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
