# Generated by Django 4.1.7 on 2023-03-18 00:48

from django.db import migrations


def load_initial_data(kanban):
    parameter_model = kanban.get_model('Parameter')
    parameter_model.objects.create(
        name="limit", value=2
    )


class Migration(migrations.Migration):
    dependencies = [
        ('kanban', '0010_remove_parameter_avatar_parameter_value'),
    ]

    operations = [
    ]
